name: Run Pytest with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest  # Можно заменить на windows-latest, если нужен Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure
        run: |
          curl -o allure.tar.gz -L https://github.com/allure-framework/allure2/releases/latest/download/allure-2.25.0.tgz
          tar -xzf allure.tar.gz
          sudo mv allure-2.25.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
          allure --version  # Проверяем установку

      - name: Run Tests with Allure
        run: pytest --alluredir=allure-results

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
